### ISSUE TITLE
总是错误

### ISSUE THREAD

**Issue by fanji2023** [WEIFENG2333/AsrTools#14]
![屏幕截图 2024-10-18 192815](https://github.com/user-attachments/assets/ca54d3a7-f4fa-451a-8bfa-c400bda60f59)
每个接口都试了2遍，处理一段时间后全部显示“错误”。

**Comment by WEIFENG2333** [comment]
这里正常使用，请提供一下保存信息

**Comment by aoge9** [comment]
处理时出错 'utf-8' codec can't decode byte in position……怎么办？
