### ISSUE TITLE
J接口用不了，其它2个接口正常

### ISSUE THREAD

**Issue by zzballack** [WEIFENG2333/AsrTools#15]
谢谢大神分享的软件，非常棒！我这里是B接口和K接口正常，但J接口用不了，显示如下图：
![2024-10-18_205007](https://github.com/user-attachments/assets/b427e1eb-1247-4a3c-b11e-406f9bb3dbc7)

**Comment by WEIFENG2333** [comment]
#19

**Comment by WEIFENG2333** [comment]
[v1.1.0](https://github.com/WEIFENG2333/AsrTools/releases/tag/v1.1.0) 该版本已经修复
