### ISSUE TITLE
网主好，用剪映（J）接口，提示有问题，出错

### ISSUE THREAD

**Issue by ltl9091** [WEIFENG2333/AsrTools#19]
网主您好，用剪映(J)接口的时候，提示出错，您可以解决一下吗？

我留意到其他人也有向您反应这个问题，是不是剪映的接口被封了呢？

希望能收到您的回复。

![用剪映借口 提示出错](https://github.com/user-attachments/assets/a839ac61-5796-4325-a4c0-93886302991b)

**Comment by WEIFENG2333** [comment]
该代码的接口已经不可用。目前已找到解决方案，鉴于该项目已经有一定的流传，使用人数过多会给服务器找出压力，可能会不打算进行修复...

**Comment by ltl9091** [comment]
谢谢网主的回复，听到您说“可能会不打算进行修复...”实在觉得有些可惜

因为J接口的翻译，是比另外两个要更准确的。

如果可以的话，内心还是期待网主能够修复。

**Comment by cheng-ren** [comment]
希望大佬能修复下，或者给出个sign提示，我们后续自行跟进，谢谢

**Comment by ltl9091** [comment]
同意这位朋友的建议，希望大佬听听我们内心真实且朴素的渴望。

**Comment by lawby1229** [comment]
感谢大神，希望有更多接口

**Comment by ltl9091** [comment]
感谢这位朋友的发声，希望大佬看见大家的心声。

**Comment by KNaiFen** [comment]
> 该代码的接口已经不可用。目前已找到解决方案，鉴于该项目已经有一定的流传，使用人数过多会给服务器找出压力，可能会不打算进行修复...

大佬，我不是抨击你或者别的什么意思，只是说，如果等另外两个接口都坏了那还修吗，因为怕太多的别的人用就不修复的话，我认为这个项目最开始就没有发出来的必要了，既然现在都做了那就没啥不好意思的

**Comment by bigmouse0001** [comment]
> > 该代码的接口已经不可用。目前已找到解决方案，鉴于该项目已经有一定的流传，使用人数过多会给服务器找出压力，可能会不打算进行修复...
> 
> 大佬，我不是抨击你或者别的什么意思，只是说，如果等另外两个接口都坏了那还修吗，因为怕太多的别的人用就不修复的话，我认为这个项目最开始就没有发出来的必要了，既然现在都做了那就没啥不好意思的

.....哥们石乐志么，只有简中圈才优这么没教养的人阿
