### ISSUE TITLE
打开显示错误： This application failed to start because no Qt platform plugin 

### ISSUE THREAD

**Issue by q247574452** [WEIFENG2333/AsrTools#2]
![image](https://github.com/user-attachments/assets/4cf833c6-8134-4a80-bc06-75170bc2d85a)

**Comment by blueJYZ** [comment]
> 看看是不是解压在了中文目录

非常感谢，就是解压在了中文目录

**Comment by SaipnLee** [comment]
OK，解决了。不要解压在中文目录，十分感谢。
