### ISSUE TITLE
你好，请问在哪里设置TXT文件？

### ISSUE THREAD

**Issue by BBMonkey** [WEIFENG2333/AsrTools#23]
我找了下好像没看到txt文件的选项，我想要获取文字内容的txt，不需要srt

**Comment by WEIFENG2333** [comment]
暂时只能调用代码，软件页面还没有这个选项。后续更新

**Comment by Moeblack** [comment]
可以试试我的fork
https://github.com/Moeblack/Video2TextTool

**Comment by BBMonkey** [comment]
> 可以试试我的fork https://github.com/Moeblack/Video2TextTool

感谢老铁，测试了蛮好用的，但是好像有点BUG（导出失败时，不会提示失败，依旧提示成功）哈哈哈，不过不影响

**Comment by WEIFENG2333** [comment]
[v1.1.0](https://github.com/WEIFENG2333/AsrTools/releases/tag/v1.1.0) 该版本已经实现
