### ISSUE TITLE
你好，请问可以增加每句的字幕长度调节功能吗？

### ISSUE THREAD

**Issue by Aphirodite** [WEIFENG2333/AsrTools#27]
你好，软件很好用，速度很快，就是生成的字幕不可调节，请问可以增加更多的字幕调节功能吗？
比如限制每句的最少字数、最多字数、低于多少字就合并到前一句之类的？
还有删除标点符号、
或者自动打轴功能（根据文稿，及文稿生成的音频文件，生成精准的字幕文件）等。

**Comment by WEIFENG2333** [comment]
可以看看这个：[VideoCaptioner](https://github.com/WEIFENG2333/VideoCaptioner)
