### ISSUE TITLE
我测试80M的mp3好像就不能转出文字了，但是文件小一些没有问题。。。

### ISSUE THREAD

**Issue by cn20004** [WEIFENG2333/AsrTools#34]
### 问题描述 Problem Description

我测试80M的mp3好像就不能转出文字了，但是文件小一些没有问题。。。

**Comment by WEIFENG2333** [comment]
在线接口资源有限，太长的视频没办法。

**Comment by WEIFENG2333** [comment]
可以试试 https://github.com/WEIFENG2333/VideoCaptioner
