### ISSUE TITLE
J接口无法使用

### ISSUE THREAD

**Issue by XHH-tech** [WEIFENG2333/AsrTools#39]
### 问题描述 Problem Description

每次使用J接口（剪映接口），经常会出现等待几个小时，任务没有进展，一直卡顿在初始界面的情况，请核实。另，希望选择一次默认接口后，下次登录软件会记录这个选项，避免每次进入都需要重新选择一次。
![111111](https://github.com/user-attachments/assets/359c36eb-53ce-4f70-b43d-39214bb33382)

**Comment by wffb** [comment]
我也出现相同情况，请问找到解决方法了吗

**Comment by WEIFENG2333** [comment]
正常，该接口为了避免频繁做出的限制。

**Comment by nissansz** [comment]
> 正常，该接口为了避免频繁做出的限制。

等待多久是正常的？怎么自己设定等待时间，避免多个文件时停止，不继续处理后面的文件？
