### ISSUE TITLE
建议增加选项源语言

### ISSUE THREAD

**Issue by paulxjz** [WEIFENG2333/AsrTools#4]
识别增加选项源语言，我试过把动漫，日语的，效果不行，和我把视频放capcut选日语差挺多的（capcut应该和剪映差不多吧），~~吐槽下mkv要手动提取音轨，希望能直接识别mkv~~，我看到todo有了

**Comment by WEIFENG2333** [comment]
似乎capcut的接口和国内剪映的接口还是有点区别的，接口的语言就是自动识别的，剪映好像还不支持日语，后续研究一下capcut的。
另外，已经在着手一个项目，实现全自动字幕处理+修正+翻译，现在已经可以达到不错的效果。后面可以留意一下。

**Comment by paulxjz** [comment]
> 似乎capcut的接口和国内剪映的接口还是有点区别的，接口的语言就是自动识别的，剪映好像还不支持日语，后续研究一下capcut的。
> 另外，已经在着手一个项目，实现全自动字幕处理+修正+翻译，现在已经可以达到不错的效果。后面可以留意一下。

好的，我期待一下

**Comment by Doutianbao** [comment]
能否在输入端判断是视频还是音频，如果是视频，先用ffmpeg提取音频再处理。

**Comment by WEIFENG2333** [comment]
> 能否在输入端判断是视频还是音频，如果是视频，先用ffmpeg提取音频再处理。

后续会支持
