### ISSUE TITLE
打开软件报错

### ISSUE THREAD

**Issue by cqjason829** [WEIFENG2333/AsrTools#41]
### 问题描述 Problem Description

![333](https://github.com/user-attachments/assets/eb785311-c50b-4996-8506-3d6f32fe7652)
![444](https://github.com/user-attachments/assets/9a4c671f-9736-40e9-b05a-69fc1253b540)

**打开软件报错，是因为我是WIN7系统的原因吗？请问一下支持那些系统**

**Comment by WEIFENG2333** [comment]
软件不支持win7
