### ISSUE TITLE
处理出错 处理时出错 WishperASR 暂未实现

### ISSUE THREAD

**Issue by jinwyp** [WEIFENG2333/AsrTools#7]
处理出错 处理时出错 WishperASR 暂未实现

这个本地模型还没做好？

建议使用 最新的 https://huggingface.co/openai/whisper-large-v3-turbo

**Comment by WEIFENG2333** [comment]
加入本地模型使软件过于臃肿，而开源社区已有许多项目涵盖此领域。可以先使用GitHub上的优秀项目，版项目后续再考虑添加。
