### ISSUE TITLE
Mac系统的打包程序~~~

### ISSUE THREAD

**Issue by prof-yang** [WEIFENG2333/AsrTools#9]
如题~~~给大佬递烟

**Comment by WEIFENG2333** [comment]
能给我递一台Mac电脑吗(🐶)

**Comment by NB-XX** [comment]
https://github.com/NB-XX/AsrTools/releases/tag/v1.0.1
我打包了一份，可以试试。

**Comment by prof-yang** [comment]
> https://github.com/NB-XX/AsrTools/releases/tag/v1.0.1 我打包了一份，可以试试。

wow~多谢！

**Comment by NingerJohn** [comment]
> https://github.com/NB-XX/AsrTools/releases/tag/v1.0.1 我打包了一份，可以试试。

有打包教程吗？求，我想试试ubuntu系统打包

**Comment by NB-XX** [comment]
> > https://github.com/NB-XX/AsrTools/releases/tag/v1.0.1 我打包了一份，可以试试。
> 
> 有打包教程吗？求，我想试试ubuntu系统打包

我使用 [pyinstaller](https://pypi.org/project/pyinstaller/) 进行的打包，但是没有做优化导致包很大。
